extends Node
class_name Outside_Constants

enum UPPER_CHUNK { 
	LIGTH_BUILDING = 0,
	BLUE_BUILDING = 1,
	CROSS_START = 2,
	CROSS_END = 3,
	PARK = 4,
	FACTORY = 5,
}

enum LOWER_CHUNK { 
	GRASS = 0,
	ROAD = 1,
	PARK = 2,
	CROSS_START = 3,
	CROSS_END = 4,
}

const TILE_SIZE: int = 16
const CHUNK_TILE_WIDTH: int = 10
const CHUNK_TILE_HEIGHT: int = 11
const UPPER_CHUNK_TILE_HEIGHT: int = 5
const LOWER_CHUNK_TILE_HEIGHT: int = 5

const POSSIBLE_UPPER_CHUNK_BASED_ON_LOWER = {
	LOWER_CHUNK.GRASS: [UPPER_CHUNK.LIGTH_BUILDING, UPPER_CHUNK.BLUE_BUILDING],
	LOWER_CHUNK.ROAD: [UPPER_CHUNK.LIGTH_BUILDING, UPPER_CHUNK.BLUE_BUILDING, UPPER_CHUNK.FACTORY],
	LOWER_CHUNK.PARK: [UPPER_CHUNK.PARK],
	LOWER_CHUNK.CROSS_START: [UPPER_CHUNK.CROSS_START],
	LOWER_CHUNK.CROSS_END: [UPPER_CHUNK.CROSS_END],
}

const POSSIBLE_NEXT_CHUNK_BASED_ON_PREVIOUS = {
	LOWER_CHUNK.GRASS: [LOWER_CHUNK.GRASS, LOWER_CHUNK.CROSS_START],
	LOWER_CHUNK.ROAD: [LOWER_CHUNK.ROAD, LOWER_CHUNK.CROSS_END],
	LOWER_CHUNK.PARK: [LOWER_CHUNK.PARK, LOWER_CHUNK.GRASS, LOWER_CHUNK.CROSS_START],
	LOWER_CHUNK.CROSS_START: [LOWER_CHUNK.ROAD],
	LOWER_CHUNK.CROSS_END: [LOWER_CHUNK.GRASS, LOWER_CHUNK.PARK],
}

const LOWER_CHUNK_DECORATION_GRASS_TILE_HEIGHT: int = 2
const LOWER_CHUNK_DECORATION_GRASS_START_Y_TILE_IDX: int = 5

const UPPER_CHUNK_DECORATION_GRASS_START_Y_TILE_IDX: int = 8
const UPPER_CHUNK_DECORATION_GRASS_START_X_TILE_IDX: int = 9

const LOWER_CHUNK_DECORATION_ROAD_START_Y_TILE_IDX: int = 9

const MAX_CHUNKS: int = 10

const ATLAS_SOURCE_ID = 2

const ROAD_BACKGROUND_TILE_SIZE = Vector2i(1, 1)
const ROAD_BACKGROUND_UPPER_LEFT_CORNER_TILES_ATLAS_COORDS = [ 
	Vector2i(4, 0),
	Vector2i(5, 0),
	Vector2i(4, 1),
	Vector2i(5, 1),
	Vector2i(4, 2),
	Vector2i(5, 2),
]

const SIDEWALK_BACKGROUND_TILE_SIZE = Vector2i(1, 1)
const SIDEWALK_BACKGROUND_UPPER_LEFT_CORNER_TILES_ATLAS_COORDS = [ 
	Vector2i(6, 0),
	Vector2i(7, 0),
	Vector2i(8, 0),
	Vector2i(9, 0),
	Vector2i(6, 1),
	Vector2i(7, 1),
	Vector2i(8, 1),
	Vector2i(9, 1),
	Vector2i(6, 2),
	Vector2i(7, 2),
	Vector2i(8, 2),
	Vector2i(9, 2),
]

const GRASS_BACKGROUND_TILE_SIZE = Vector2i(4, 4)
const GRASS_BACKGROUND_TILES_UPPER_LEFT_CORNER_TILES_ATLAS_COORDS = [
	Vector2i(0, 4),
	Vector2i(1, 4),
	Vector2i(2, 4),
	Vector2i(3, 4),
	Vector2i(0, 5),
	Vector2i(1, 5),
	Vector2i(2, 5),
	Vector2i(3, 5),
	Vector2i(0, 6),
	Vector2i(1, 6),
	Vector2i(2, 6),
	Vector2i(3, 6),
	Vector2i(0, 7),
	Vector2i(1, 7),
	Vector2i(2, 7),
	Vector2i(3, 7),
]

const GRASS_SIDEWALK_DECORATION_TILE_SIZE = Vector2i(3, 3)
const GRASS_SIDEWALK_DECORATION_UPPER_LEFT_CORNER_TILES_ATLAS_COORDS = [ 
	Vector2i(4, 4),
	Vector2i(5, 4),
	Vector2i(6, 4),
	Vector2i(4, 5),
	Vector2i(5, 5),
	Vector2i(6, 5),
	Vector2i(4, 6),
	Vector2i(5, 6),
	Vector2i(6, 6),
 ]

# --- Whole concrete

const CONCRETE_WHOLE_DOWN_BACKGROUND_TILE_SIZE = Vector2i(1, 1)
const CONCRETE_WHOLE_DOWN_BACKGROUND_TILES_ATLAS_COORDS = [ 
	Vector2i(13, 0),
	Vector2i(16, 0),
]

const CONCRETE_WHOLE_LEFT_BACKGROUND_TILE_SIZE = Vector2i(1, 1)
const CONCRETE_WHOLE_LEFT_BACKGROUND_TILES_ATLAS_COORDS = [ 
	Vector2i(13, 1),
	Vector2i(16, 1),
]

const CONCRETE_WHOLE_UP_BACKGROUND_TILE_SIZE = Vector2i(1, 1)
const CONCRETE_WHOLE_UP_BACKGROUND_TILES_ATLAS_COORDS = [ 
	Vector2i(13, 2),
	Vector2i(16, 2),
]

const CONCRETE_WHOLE_RIGHT_BACKGROUND_TILE_SIZE = Vector2i(1, 1)
const CONCRETE_WHOLE_RIGHT_BACKGROUND_TILES_ATLAS_COORDS = [ 
	Vector2i(13, 3),
	Vector2i(16, 3),
]


# --- End concrete

const CONCRETE_END_DOWN_BACKGROUND_TILE_SIZE = Vector2i(1, 1)
const CONCRETE_END_DOWN_BACKGROUND_TILES_ATLAS_COORDS = [ 
	Vector2i(14, 0),
	Vector2i(17, 0),
]

const CONCRETE_END_LEFT_BACKGROUND_TILE_SIZE = Vector2i(1, 1)
const CONCRETE_END_LEFT_BACKGROUND_TILES_ATLAS_COORDS = [ 
	Vector2i(14, 1),
	Vector2i(14, 1),
]

const CONCRETE_END_RIGHT_BACKGROUND_TILE_SIZE = Vector2i(1, 1)
const CONCRETE_END_RIGHT_BACKGROUND_TILES_ATLAS_COORDS = [ 
	Vector2i(14, 3),
	Vector2i(17, 3),
]

const CONCRETE_END_UP_BACKGROUND_TILE_SIZE = Vector2i(1, 1)
const CONCRETE_END_UP_BACKGROUND_TILES_ATLAS_COORDS = [ 
	Vector2i(14, 2),
	Vector2i(17, 2),
]

# --- Start concrete

const CONCRETE_START_DOWN_BACKGROUND_TILE_SIZE = Vector2i(1, 1)
const CONCRETE_START_DOWN_BACKGROUND_ATLAS_COORDS = [ 
	Vector2i(15, 0),
	Vector2i(18, 0),
]

const CONCRETE_START_LEFT_BACKGROUND_TILE_SIZE = Vector2i(1, 1)
const CONCRETE_START_LEFT_BACKGROUND_TILES_ATLAS_COORDS = [ 
	Vector2i(15, 1),
	Vector2i(18, 1),
]

const CONCRETE_START_RIGHT_BACKGROUND_TILE_SIZE = Vector2i(1, 1)
const CONCRETE_START_RIGHT_BACKGROUND_TILES_ATLAS_COORDS = [ 
	Vector2i(15, 3),
	Vector2i(18, 3),
]

const CONCRETE_START_UP_BACKGROUND_TILE_SIZE = Vector2i(1, 1)
const CONCRETE_START_UP_BACKGROUND_TILES_ATLAS_COORDS = [ 
	Vector2i(15, 2),
	Vector2i(18, 2),
]

# Crosswalk
const CROSSWALK_BACKGROUND_TILE_SIZE = Vector2i(1, 1)
const CROSSWALK_BACKGROUND_TILES_ATLAS_COORDS = [ Vector2i(10 ,5) ]

# Buildings

const BLUE_BUILDING_ENTRANCE_WINDOW_TILE_SIZE = Vector2i(2, 2)
const BLUE_BUILDING_ENTRANCE_WINDOW_UPPER_LEFT_CORNER_TILES_ATLAS_COORDS = [ Vector2i(8, 8) ]

const BLUE_BUILDING_ENTRANCE_TILE_SIZE = Vector2i(2, 3)
const BLUE_BUILDING_ENTRANCE_UPPER_LEFT_CORNER_TILES_ATLAS_COORDS = [ Vector2i(8, 10) ] 

const BLUE_BUILDING_BASEMENT_TILE_SIZE = Vector2i(2, 1)
const BLUE_BUILDING_BASEMENT_UPPER_LEFT_CORNER_TILES_ATLAS_COORDS = [
	Vector2i(0, 12),
	Vector2i(2, 12),
	Vector2i(4, 12),
	Vector2i(6, 12),
]

const BLUE_BUILDING_WINDOWS_TILE_SIZE = Vector2i(2, 2)
const BLUE_BUILDING_WINDOWS_UPPER_LEFT_CORNER_TILES_ATLAS_COORDS = [
	Vector2i(0, 8),
	Vector2i(2, 8),
	Vector2i(4, 8),
	Vector2i(6, 8),
	Vector2i(0, 10),
	Vector2i(2, 10),
	Vector2i(4, 10),
	Vector2i(6, 10),
]

const LIGHT_BUILDING_ENTRANCE_WINDOW_TILE_SIZE = Vector2i(2, 2)
const LIGHT_BUILDING_ENTRANCE_WINDOW_UPPER_LEFT_CORNER_TILES_ATLAS_COORDS = [ Vector2i(18, 8) ]

const LIGHT_BUILDING_ENTRANCE_TILE_SIZE = Vector2i(2, 3)
const LIGHT_BUILDING_ENTRANCE_UPPER_LEFT_CORNER_TILES_ATLAS_COORDS = [ Vector2i(18, 10) ] 

const LIGHT_BUILDING_BASEMENT_TILE_SIZE = Vector2i(2, 1)
const LIGHT_BUILDING_BASEMENT_UPPER_LEFT_CORNER_TILES_ATLAS_COORDS = [
	Vector2i(10, 12),
	Vector2i(12, 12),
	Vector2i(14, 12),
	Vector2i(16, 12),
]

const LIGHT_BUILDING_WINDOWS_TILE_SIZE = Vector2i(4, 2)
const LIGHT_BUILDING_WINDOWS_UPPER_LEFT_CORNER_TILES_ATLAS_COORDS = [
	Vector2i(10, 8),
	Vector2i(14, 8),
	Vector2i(10, 10),
	Vector2i(14, 10),
]

const FACTORY_BUILDING_ENTRANCE_TILE_SIZE = Vector2i(9, 3)
const Factory_BUILDING_ENTRACE_UPPER_LEFT_CORNER_TILES_ATLAS_COODS = [
	Vector2i(0, 13),
	Vector2i(10, 13)
]

const FACTORY_BUILDING_WINDOWS_TILE_SIZE = Vector2i(5, 3)
const FACTORY_BUILDING_WINDOWS_UPPER_LEFT_CORNER_TILES_ATLAS_COORDS = [
	Vector2i(0, 16),
	Vector2i(5, 16),
	Vector2i(10, 16),
	Vector2i(15, 16),
]
